import { Video } from "./types";

export const mockVideos: Video[] = [
  {
    project_id: "vid_001",
    title: "Why Squidward Is Actually The Main Character",
    status: "Published",
    created_at: "2024-11-15T10:30:00Z",
    total_sections: 8,
    duration_hours: 0,
    duration_minutes: 24,
    main_characters: "Squidward, SpongeBob, Patrick",
    primary_locations: "Squidward's House, Krusty Krab",
    central_theme: "Character analysis and hidden protagonist theory",
    tone: "Analytical, thought-provoking",
  },
  {
    project_id: "vid_002",
    title: "The Dark Truth About Bikini Bottom",
    status: "Voiceover in progress",
    created_at: "2024-11-28T14:15:00Z",
    total_sections: 12,
    duration_hours: 0,
    duration_minutes: 38,
    main_characters: "SpongeBob, Mr. Krabs, Plankton",
    primary_locations: "Bikini Bottom, Chum Bucket",
    central_theme: "Hidden lore and conspiracy theories",
    tone: "Mysterious, investigative",
  },
  {
    project_id: "vid_003",
    title: "Every Krabby Patty Secret Ingredient Theory Ranked",
    status: "Images generating",
    created_at: "2024-11-30T09:00:00Z",
    total_sections: 10,
    duration_hours: 0,
    duration_minutes: 31,
    main_characters: "Mr. Krabs, Plankton, SpongeBob",
    primary_locations: "Krusty Krab, Chum Bucket",
    central_theme: "Fan theories exploration",
    tone: "Fun, engaging",
  },
  {
    project_id: "vid_004",
    title: "Patrick Star: Secret Genius or Just Lucky?",
    status: "Outline in progress",
    created_at: "2024-12-01T16:45:00Z",
    total_sections: 6,
    duration_hours: 0,
    duration_minutes: 18,
    main_characters: "Patrick, SpongeBob",
    primary_locations: "Patrick's Rock, Jellyfish Fields",
    central_theme: "Character deep dive",
    tone: "Comedic, analytical",
  },
  {
    project_id: "vid_005",
    title: "The Untold Story of Sandy Cheeks",
    status: "Failed",
    created_at: "2024-11-20T11:20:00Z",
    total_sections: 9,
    duration_hours: 0,
    duration_minutes: 27,
    main_characters: "Sandy, SpongeBob",
    primary_locations: "Sandy's Treedome, Texas",
    central_theme: "Character backstory exploration",
    tone: "Emotional, nostalgic",
  },
  {
    project_id: "vid_006",
    title: "Mr. Krabs: Capitalism Critique or Comedy Gold?",
    status: "Sections in creation",
    created_at: "2024-11-29T13:30:00Z",
    total_sections: 11,
    duration_hours: 0,
    duration_minutes: 35,
    main_characters: "Mr. Krabs, SpongeBob, Squidward",
    primary_locations: "Krusty Krab, Mr. Krabs' House",
    central_theme: "Social commentary analysis",
    tone: "Satirical, insightful",
  },
];
